### ISSUE TITLE
[Question] why fp8 kv output is dequantized before attention? 

### ISSUE THREAD

**Issue by danielhua23** [neuralmagic/AutoFP8#47]
Hi, I noticed that the FP8LinearStatic will dequantize the output(fp8) to input dtype(fp16/bf16) as below L209 shows.
1. Is it due to the attention kernel does not support fp8 at that time? And is it supported now? 
2. if supported, Could you pls guide me the code line in vllm or others?
3. Finally, regarding the code line below, I think this is equal to fake quant? And you just stored the kv scale for attention to dequantize fp8 kv read from fp8 kv cache
![image](https://github.com/user-attachments/assets/63738b1b-a398-42be-b4e4-3fa84d844a51)

**Comment by comaniac** [comment]
There are two reasons. First, the FP8 GEMM accumulator must be in FP16 to prevent overflow, so the output is naturally FP16 instead of being "dequanted". Making output in FP8, on the other hand, requires additional quantization overheads.

Second, the operators followed by GEMM usually don't compute in FP8, either because of not supported (like attention) or numerical sensitive (like RoPE or RMSNorm).

**Comment by danielhua23** [comment]
thanks for your detailed explanation, Cody! have you ever tried simply set the output scale (fp16->fp8) to 1? which I see has the almostly similar accuracy in some scenario

**Comment by comaniac** [comment]
> thanks for your detailed explanation, Cody! have you ever tried simply set the output scale (fp16->fp8) to 1? which I see has the almostly similar accuracy in some scenario

It may work with your tasks but I don't think this would work in general, as I can easily imagine a case with accuracy dropping, where your fp16 value exceeds the fp8 value range.

**Comment by danielhua23** [comment]
thank cody for the sharing, it helps me a lot!
